using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using TypeScriptDefinitionGenerator.Helpers;

namespace TypeScriptDefinitionGenerator
{
    internal static class IntellisenseWriter
    {
        private static readonly Regex _whitespaceTrimmer = new Regex(@"^\s+|\s+$|\s*[\r\n]+\s*", RegexOptions.Compiled);

        public static string WriteTypeScript(IEnumerable<IntellisenseObject> objects)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendFormat("//     This file was generated by TypeScript Definition Generator v{0}\r\n", Vsix.Version);
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");

            foreach (var ns in objects.GroupBy(o => o.Namespace))
            {
                if (Options.DeclareModule)
                {
                    sb.AppendFormat("declare module {0} {{\r\n", ns.Key);
                }

                string export = !Options.DeclareModule ? "export " : string.Empty;
                string prefixModule = Options.DeclareModule ? "\t" : String.Empty;

                foreach (IntellisenseObject io in ns)
                {
                    if (!string.IsNullOrEmpty(io.Summary))
                        sb.Append(prefixModule).AppendLine("/** " + _whitespaceTrimmer.Replace(io.Summary, "") + " */");

                    if (io.IsEnum)
                    {
                        string type = "enum ";
                        sb.Append(prefixModule).Append(export).Append(type).Append(Utility.CamelCaseClassName(io.Name)).Append(" ");

                        sb.AppendLine("{");
                        WriteTSEnumDefinition(sb, prefixModule + "\t", io.Properties);
                        sb.Append(prefixModule).AppendLine("}");
                    }
                    else
                    {
                        string type = Options.ClassInsteadOfInterface ? "class " : "interface ";
                        sb.Append(prefixModule).Append(export).Append(type).Append(Utility.CamelCaseClassName(io.Name)).Append(" ");

                        if (!string.IsNullOrEmpty(io.BaseName))
                        {
                            sb.Append("extends ");

                            if (!string.IsNullOrEmpty(io.BaseNamespace) && io.BaseNamespace != io.Namespace)
                                sb.Append(io.BaseNamespace).Append(".");

                            sb.Append(Utility.CamelCaseClassName(io.BaseName)).Append(" ");
                        }

                        sb.AppendLine("{");
                        WriteTSInterfaceDefinition(sb, prefixModule + "\t", io.Properties);
                        sb.Append(prefixModule).AppendLine("}");
                    }
                }

                if (Options.DeclareModule)
                {
                    sb.AppendLine("}");
                }
            }

            if (Options.EOLType == EOLType.LF)
                sb.Replace("\r\n", "\n");

            if (!Options.IndentTab)
                sb.Replace("\t", new string(' ', Options.IndentTabSize));

            return sb.ToString();
        }

        private static string CleanEnumInitValue(string value)
        {
            value = value.TrimEnd('u', 'U', 'l', 'L'); //uint ulong long
            if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase)) return value;
            var trimedValue = value.TrimStart('0'); // prevent numbers to be parsed as octal in js.
            if (trimedValue.Length > 0) return trimedValue;
            return "0";
        }
        
        private static void WriteTypeScriptComment(IntellisenseProperty p, StringBuilder sb, string prefix)
        {
            if (string.IsNullOrEmpty(p.Summary)) return;
            sb.Append(prefix).AppendLine("/** " + _whitespaceTrimmer.Replace(p.Summary, "") + " */");
        }

        private static void WriteTSEnumDefinition(StringBuilder sb, string prefix, IEnumerable<IntellisenseProperty> props)
        {
            foreach (var p in props)
            {
                WriteTypeScriptComment(p, sb, prefix);

                if (p.InitExpression != null)
                {
                    sb.AppendLine(prefix + Utility.CamelCaseEnumValue(p.Name) + " = " + CleanEnumInitValue(p.InitExpression) + ",");
                }
                else
                {
                    sb.AppendLine(prefix + Utility.CamelCaseEnumValue(p.Name) + ",");
                }
            }

        }

        private static void WriteTSInterfaceDefinition(StringBuilder sb, string prefix, IEnumerable<IntellisenseProperty> props)
        {
            foreach (var p in props)
            {
                WriteTypeScriptComment(p, sb, prefix);
                sb.AppendFormat("{0}{1}: ", prefix, Utility.CamelCasePropertyName(p.NameWithOption));

                if (p.Type.IsKnownType) sb.Append(p.Type.TypeScriptName);
                else
                {
                    if (p.Type.Shape == null) sb.Append("any");
                    else WriteTSInterfaceDefinition(sb, prefix, p.Type.Shape);
                }
                if (p.Type.IsArray) sb.Append("[]");

                sb.AppendLine(";");
            }
        }
    }
}
