<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;NU1701;</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <TypeScriptDefinitionSource Include="SecondClass.cs" />
    <TypeScriptDefinitionSource Include="SomeClassDto.cs" />
    <TypeScriptDefinitionSource Include="SomeEnum.cs" />
    <TypeScriptDefinitionSource Include="base\ThirdClass.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SecondClass.generated.d.ts">
      <DependentUpon>SecondClass.cs</DependentUpon>
    </None>
    <None Update="SomeClassDto.generated.d.ts">
      <DependentUpon>SomeClassDto.cs</DependentUpon>
    </None>
    <None Update="SomeEnum.generated.d.ts">
      <DependentUpon>SomeEnum.cs</DependentUpon>
    </None>
    <None Update="base\ThirdClass.generated.d.ts">
      <DependentUpon>ThirdClass.cs</DependentUpon>
    </None>
  </ItemGroup>
</Project>
