<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;NU1701;</NoWarn>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
    <RootNamespace>TypeScriptDefinitionGenerator.Rider</RootNamespace>
    <AssemblyName>TypeScriptDefinitionGenerator.Rider</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DefineConstants>$(DefineConstants);RIDER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="2024.2.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Actions.xml" LogicalName="Actions.xml"/>
  </ItemGroup>

</Project>
