// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by TypeScript Definition Generator v2.1.0.0
// </auto-generated>
// ------------------------------------------------------------------------------
declare module Server.Dtos {
export 	interface Class1 {
		temp: string;
		mas: Server.Dtos.Mas;
		some: any;
	}
	export const enum Mas {
		First,
		Next,
	}
}
