<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <SignAssembly>false</SignAssembly>
    <AssemblyName>TypeScriptDefinitionGenerator.Tests</AssemblyName>
    <RootNamespace>TypeScriptDefinitionGenerator.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.1.0" />
    <PackageReference Include="EnvDTE" Version="17.6.36389" />
    <PackageReference Include="FluentAssertions" Version="4.19.4" />
    <PackageReference Include="Moq" Version="4.7.99" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TypeScriptDefinitionGenerator\TypeScriptDefinitionGenerator.csproj" />
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Class1.cs">
      <Generator></Generator>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Class1.cs.generated.d.ts">
      <DependentUpon>Class1.cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
