using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace TypeScriptDefinitionGenerator.Core;

public static class IntellisenseWriter
{
    private static readonly Regex WhitespaceTrimmer = new Regex(@"^\s+|\s+$|\s*[\r\n]+\s*", RegexOptions.Compiled);

    public static string WriteTypeScript(IList<IntellisenseObject> objects, string? sourceItemPath, IGeneratorOptions options, string version = "1.0")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendFormat("//     This file was generated by TypeScript Definition Generator v{0}\r\n", version);
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// ------------------------------------------------------------------------------");

        var export = !options.DeclareModule ? "export " : string.Empty;
        var prefixModule = options.DeclareModule ? "\t" : string.Empty;

        var sbBody = new StringBuilder();
        var neededImports = new List<string>();

        foreach (var ns in objects.GroupBy(o => o.Namespace))
        {
            if (options.DeclareModule)
                sbBody.AppendFormat("declare module {0} {{\r\n", ns.Key);

            foreach (var io in ns)
            {
                if (!string.IsNullOrEmpty(io.Summary))
                    sbBody.Append(prefixModule).AppendLine("/** " + WhitespaceTrimmer.Replace(io.Summary, "") + " */");

                if (io.IsEnum)
                {
                    sbBody.Append(prefixModule).Append(export).Append("enum ").Append(Utility.CamelCaseClassName(io.Name, options)).Append(" ");
                    sbBody.AppendLine("{");
                    WriteTSEnumDefinition(sbBody, prefixModule + "\t", io.Properties, options);
                    sbBody.Append(prefixModule).AppendLine("}");
                }
                else
                {
                    var type = options.ClassInsteadOfInterface ? "class " : "interface ";
                    sbBody.Append(prefixModule).Append(export).Append(type).Append(Utility.CamelCaseClassName(io.Name, options)).Append(" ");

                    if (!string.IsNullOrEmpty(io.BaseName))
                    {
                        sbBody.Append("extends ");
                        if (!string.IsNullOrEmpty(io.BaseNamespace) && io.BaseNamespace != io.Namespace)
                            sbBody.Append(io.BaseNamespace).Append(".");
                        sbBody.Append(Utility.CamelCaseClassName(io.BaseName!, options)).Append(" ");
                    }

                    sbBody.AppendLine("{");
                    WriteTSInterfaceDefinition(sbBody, prefixModule + "\t", io.Properties, options);
                    sbBody.Append(prefixModule).AppendLine("}");

                    neededImports.AddRange(io.Properties
                        .Where(p => p.Type?.ClientSideReferenceName != null && !p.Type.IsDictionary)
                        .Select(p => p.Type!.ClientSideReferenceName!));
                }
            }

            if (options.DeclareModule)
                sbBody.AppendLine("}");
        }

        if (!options.DeclareModule && !string.IsNullOrEmpty(sourceItemPath))
        {
            var references = objects.SelectMany(o => o.References).Distinct();
            var imports = new List<string>();

            foreach (var reference in references)
            {
                var referencePathRelative = Utility.GetRelativePath(sourceItemPath!, reference);
                if (referencePathRelative.EndsWith(".ts", StringComparison.OrdinalIgnoreCase))
                    referencePathRelative = referencePathRelative.Substring(0, referencePathRelative.Length - 3);
                referencePathRelative = referencePathRelative.Replace(Path.DirectorySeparatorChar, '/');
                var referenceName = Path.GetFileNameWithoutExtension(Path.GetFileName(reference));

                if (!neededImports.Contains(referenceName))
                    continue;

                sb.AppendLine($"import {{ {referenceName} }} from \"{referencePathRelative}\";");
                imports.Add(referenceName);
            }

            var baseClasses = objects.Select(o => o.BaseName).Where(b => b != null && !imports.Contains(b!)).Distinct();
            foreach (var b in baseClasses)
            {
                var expectedBaseClassPath = Path.Combine(Path.GetDirectoryName(sourceItemPath) ?? "", b + ".cs");
                if (!File.Exists(expectedBaseClassPath))
                    throw new InvalidOperationException($"Could not find base class for {b}. Expected path: {expectedBaseClassPath}");

                sb.AppendLine($"import {{ {b} }} from \"./{b}.generated\";");
                imports.Add(b!);
            }

            var notImported = neededImports.Except(imports).ToList();
            if (notImported.Count > 0)
                sb.AppendLine($"// Missing imports: {string.Join(", ", notImported)}");
        }

        sb.Append(sbBody);

        if (options.EOLType == EOLType.LF)
            sb.Replace("\r\n", "\n");

        if (!options.IndentTab)
            sb.Replace("\t", new string(' ', options.IndentTabSize));

        return sb.ToString();
    }

    private static string CleanEnumInitValue(string value)
    {
        value = value.TrimEnd('u', 'U', 'l', 'L');
        if (value.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
            return value;
        var trimmed = value.TrimStart('0');
        return trimmed.Length > 0 ? trimmed : "0";
    }

    private static void WriteTSEnumDefinition(StringBuilder sb, string prefix, IEnumerable<IntellisenseProperty> props, IGeneratorOptions options)
    {
        foreach (var p in props)
        {
            if (!string.IsNullOrEmpty(p.Summary))
                sb.Append(prefix).AppendLine("/** " + WhitespaceTrimmer.Replace(p.Summary, "") + " */");

            if (p.InitExpression != null)
                sb.AppendLine(prefix + Utility.CamelCaseEnumValue(p.Name, options) + " = " + CleanEnumInitValue(p.InitExpression) + ",");
            else
                sb.AppendLine(prefix + Utility.CamelCaseEnumValue(p.Name, options) + ",");
        }
    }

    private static void WriteTSInterfaceDefinition(StringBuilder sb, string prefix, IEnumerable<IntellisenseProperty> props, IGeneratorOptions options)
    {
        foreach (var p in props)
        {
            if (p.Type == null)
                continue;

            if (!string.IsNullOrEmpty(p.Summary))
                sb.Append(prefix).AppendLine("/** " + WhitespaceTrimmer.Replace(p.Summary, "") + " */");

            sb.AppendFormat("{0}{1}: ", prefix, Utility.CamelCasePropertyName(p.NameWithOption, options));

            if (p.Type.IsKnownType)
                sb.Append(p.Type.TypeScriptName);
            else if (p.Type.Shape == null)
                sb.Append("any");
            else
                WriteTSInterfaceDefinition(sb, prefix, p.Type.Shape, options);

            if (p.Type.IsArray)
                sb.Append("[]");
            sb.AppendLine(";");
        }
    }
}